lane :test do
    flutter_version_manager(
      arguments: "-major",
      yml: "./version.yml",
      pubspec: "./pubspec.yaml")
  end
  
  lane :bump_major do
    flutter_version_manager(
      arguments: "-major",
      yml: "./version.yml",
      pubspec: "./pubspec.yaml")
      bump_code
  end
  
  lane :bump_minor do
    flutter_version_manager(
      arguments: "-minor",
      yml: "./version.yml",
      pubspec: "./pubspec.yaml")
      bump_code
  end
  
  lane :bump_patch do
    flutter_version_manager(
      arguments: "-patch",
      yml: "./version.yml",
      pubspec: "./pubspec.yaml")
      bump_code
  end
 
  lane :bump_code do
    build_number = Time.new.strftime("%s")
      Dir.chdir "../android" do 
        sh("bundle", "exec","fastlane","internal", "build_number:#{build_number}") 
      end 
  end
  
  lane :read_version do
    flutter_version_manager(
      arguments: "-version",
      yml: "./version.yml",
      pubspec: "./pubspec.yaml")
  end
  
  lane :read_code do
    flutter_version_manager(
      arguments: "-code",
      yml: "./version.yml",
      pubspec: "./pubspec.yaml")
  end
  
  lane :apply_new_version do
    flutter_version_manager(
      arguments: "-apply",
      yml: "./version.yml",
      pubspec: "./pubspec.yaml")
  end
  
  lane :get_help do
    flutter_version_manager(
      arguments: "-h",
      yml: "./version.yml",
      pubspec: "./pubspec.yaml")
  end